# Generated by Django 3.0.3 on 2020-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0004_auto_20200211_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='birthday',
            field=models.CharField(max_length=50),
        ),
    ]
